apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot
  name: springboot
spec:
  ports:
  - name: springboot
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: springboot
  sessionAffinity: None
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: springboot
  name: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - image: master.cfc:8500/default/springboot:latest
        imagePullPolicy: Always
        name: springboot
        ports:
        - containerPort: 9080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: admin.registrykey
